### ISSUE TITLE
coffeescript NameError

### ISSUE THREAD

**Issue by greezeyfreezey** [johnbintz/jasmine-headless-webkit#79]
I am using jasmine with jenkins and everytime i try to run a build i see the follow error..

*\* Execute jhw
/opt/ruby-enterprise-1.8.7/lib/ruby/gems/1.8/gems/jasmine-headless-webkit-0.7.3.1/bin/jasmine-headless-webkit:24: uninitialized constant CoffeeScript (NameError)
    from /opt/ruby-enterprise-1.8.7/bin/jasmine-headless-webkit:19:in `load'
    from /opt/ruby-enterprise-1.8.7/bin/jasmine-headless-webkit:19
rake aborted!
Command failed with status (1): [jasmine-headless-webkit...]
/opt/ruby-enterprise-1.8.7/lib/ruby/gems/1.8/gems/rake-0.8.7/lib/rake.rb:995:in`sh'
/opt/ruby-enterprise-1.8.7/lib/ruby/gems/1.8/gems/rake-0.8.7/lib/rake.rb:1010:in `call'
/opt/ruby-enterprise-1.8.7/lib/ruby/gems/1.8/gems/rake-0.8.7/lib/rake.rb:1010:in`sh'
/opt/ruby-enterprise-1.8.7/lib/ruby/gems/1.8/gems/rake-0.8.7/lib/rake.rb:1094:in `sh'
/var/lib/jenkins/workspace/trunk_jasmine/ideeli/lib/tasks/jhw.rake:4
/opt/ruby-enterprise-1.8.7/lib/ruby/gems/1.8/gems/rake-0.8.7/lib/rake.rb:636:in`call'
/opt/ruby-enterprise-1.8.7/lib/ruby/gems/1.8/gems/rake-0.8.7/lib/rake.rb:636:in `execute'
/opt/ruby-enterprise-1.8.7/lib/ruby/gems/1.8/gems/rake-0.8.7/lib/rake.rb:631:in`each'
/opt/ruby-enterprise-1.8.7/lib/ruby/gems/1.8/gems/rake-0.8.7/lib/rake.rb:631:in `execute'
/opt/ruby-enterprise-1.8.7/lib/ruby/gems/1.8/gems/rake-0.8.7/lib/rake.rb:597:in`invoke_with_call_chain'
/opt/ruby-enterprise-1.8.7/lib/ruby/1.8/monitor.rb:242:in `synchronize'
/opt/ruby-enterprise-1.8.7/lib/ruby/gems/1.8/gems/rake-0.8.7/lib/rake.rb:590:in`invoke_with_call_chain'
/opt/ruby-enterprise-1.8.7/lib/ruby/gems/1.8/gems/rake-0.8.7/lib/rake.rb:583:in `invoke'
/opt/ruby-enterprise-1.8.7/lib/ruby/gems/1.8/gems/rake-0.8.7/lib/rake.rb:2051:in`invoke_task'
/opt/ruby-enterprise-1.8.7/lib/ruby/gems/1.8/gems/rake-0.8.7/lib/rake.rb:2029:in `top_level'
/opt/ruby-enterprise-1.8.7/lib/ruby/gems/1.8/gems/rake-0.8.7/lib/rake.rb:2029:in`each'
/opt/ruby-enterprise-1.8.7/lib/ruby/gems/1.8/gems/rake-0.8.7/lib/rake.rb:2029:in `top_level'
/opt/ruby-enterprise-1.8.7/lib/ruby/gems/1.8/gems/rake-0.8.7/lib/rake.rb:2068:in`standard_exception_handling'
/opt/ruby-enterprise-1.8.7/lib/ruby/gems/1.8/gems/rake-0.8.7/lib/rake.rb:2023:in `top_level'
/opt/ruby-enterprise-1.8.7/lib/ruby/gems/1.8/gems/rake-0.8.7/lib/rake.rb:2001:in`run'
/opt/ruby-enterprise-1.8.7/lib/ruby/gems/1.8/gems/rake-0.8.7/lib/rake.rb:2068:in `standard_exception_handling'
/opt/ruby-enterprise-1.8.7/lib/ruby/gems/1.8/gems/rake-0.8.7/lib/rake.rb:1998:in`run'
/opt/ruby-enterprise-1.8.7/lib/ruby/gems/1.8/gems/rake-0.8.7/bin/rake:31
/opt/ruby-enterprise/bin/rake:19:in `load'
/opt/ruby-enterprise/bin/rake:19
Build step 'Invoke Rake' marked build as failure
Finished: FAILURE

**Comment by greezeyfreezey** [comment]
also when trying to execute directly from CLI i still get the following

/opt/ruby-enterprise-1.8.7/lib/ruby/gems/1.8/gems/jasmine-headless-webkit-0.7.3.1/bin/jasmine-headless-webkit:24: uninitialized constant CoffeeScript (NameError)
    from /opt/ruby-enterprise-1.8.7/bin/jasmine-headless-webkit:19:in `load'
    from /opt/ruby-enterprise-1.8.7/bin/jasmine-headless-webkit:19

**Comment by johnbintz** [comment]
Is the coffee-script gem also installed and accessible in your gem path?

**Comment by greezeyfreezey** [comment]
yes 

gem list |grep -i coffee
coffee-script (2.2.0)
coffee-script-source (1.1.2)

**Comment by johnbintz** [comment]
Try the latest git HEAD. I am explicitly requiring 'coffee-script' now in the runner, which should bring in that constant.

**Comment by greezeyfreezey** [comment]
i posted earlier but removed it.. now seeing 

asmine-webkit-specrunner: cannot connect to X server rake aborted! Command failed with status (1): [jasmine-headless-webkit] /opt/ruby-enterprise-1.8.7/lib/ruby/gems/1.8/gems/rake-0.8.7/lib/rake.rb:995:in `sh' /opt/ruby-enterprise-1.8.7/lib/ruby/gems/1.8/gems/rake-0.8.7/lib/rake.rb:1010:in`call' /opt/ruby-enterprise-1.8.7/lib/ruby/gems/1.8/gems/rake-0.8.7/lib/rake.rb:1010:in `sh' /opt/ruby-enterprise-1.8.7/lib/ruby/gems/1.8/gems/rake-0.8.7/lib/rake.rb:1094:in`sh' /var/lib/jenkins/workspace/trunk_jasmine/ideeli/lib/tasks/jhw.rake:4 /opt/ruby-enterprise-1.8.7/lib/ruby/gems/1.8/gems/rake-0.8.7/lib/rake.rb:636:in `call' /opt/ruby-enterprise-1.8.7/lib/ruby/gems/1.8/gems/rake-0.8.7/lib/rake.rb:636:in`execute' /opt/ruby-enterprise-1.8.7/lib/ruby/gems/1.8/gems/rake-0.8.7/lib/rake.rb:631:in `each' /opt/ruby-enterprise-1.8.7/lib/ruby/gems/1.8/gems/rake-0.8.7/lib/rake.rb:631:in`execute' /opt/ruby-enterprise-1.8.7/lib/ruby/gems/1.8/gems/rake-0.8.7/lib/rake.rb:597:in `invoke_with_call_chain' /opt/ruby-enterprise-1.8.7/lib/ruby/1.8/monitor.rb:242:in`synchronize' /opt/ruby-enterprise-1.8.7/lib/ruby/gems/1.8/gems/rake-0.8.7/lib/rake.rb:590:in `invoke_with_call_chain' /opt/ruby-enterprise-1.8.7/lib/ruby/gems/1.8/gems/rake-0.8.7/lib/rake.rb:583:in`invoke' /opt/ruby-enterprise-1.8.7/lib/ruby/gems/1.8/gems/rake-0.8.7/lib/rake.rb:2051:in `invoke_task' /opt/ruby-enterprise-1.8.7/lib/ruby/gems/1.8/gems/rake-0.8.7/lib/rake.rb:2029:in`top_level' /opt/ruby-enterprise-1.8.7/lib/ruby/gems/1.8/gems/rake-0.8.7/lib/rake.rb:2029:in `each' /opt/ruby-enterprise-1.8.7/lib/ruby/gems/1.8/gems/rake-0.8.7/lib/rake.rb:2029:in`top_level' /opt/ruby-enterprise-1.8.7/lib/ruby/gems/1.8/gems/rake-0.8.7/lib/rake.rb:2068:in `standard_exception_handling' /opt/ruby-enterprise-1.8.7/lib/ruby/gems/1.8/gems/rake-0.8.7/lib/rake.rb:2023:in`top_level' /opt/ruby-enterprise-1.8.7/lib/ruby/gems/1.8/gems/rake-0.8.7/lib/rake.rb:2001:in `run' /opt/ruby-enterprise-1.8.7/lib/ruby/gems/1.8/gems/rake-0.8.7/lib/rake.rb:2068:in`standard_exception_handling' /opt/ruby-enterprise-1.8.7/lib/ruby/gems/1.8/gems/rake-0.8.7/lib/rake.rb:1998:in `run' /opt/ruby-enterprise-1.8.7/lib/ruby/gems/1.8/gems/rake-0.8.7/bin/rake:31 /opt/ruby-enterprise/bin/rake:19:in`load' /opt/ruby-enterprise/bin/rake:19 Build step 'Invoke Rake' marked build as failure Finished: FAILURE

**Comment by johnbintz** [comment]
For the first one: do you have a runtime installed? If you're using Node.js, have you tried specifying EXECJS_RUNTIME?

https://github.com/sstephenson/execjs/blob/master/lib/execjs/runtimes.rb#L56

I can't read the second one.

**Comment by greezeyfreezey** [comment]
The first one i resolved with nodejs.. so i removed it from it this.. here is the second one again

*\* Execute jhw
Running Jasmine specs...
jasmine-webkit-specrunner: cannot connect to X server 
rake aborted!
Command failed with status (1): [jasmine-headless-webkit]
/opt/ruby-enterprise-1.8.7/lib/ruby/gems/1.8/gems/rake-0.8.7/lib/rake.rb:995:in `sh'
/opt/ruby-enterprise-1.8.7/lib/ruby/gems/1.8/gems/rake-0.8.7/lib/rake.rb:1010:in`call'
/opt/ruby-enterprise-1.8.7/lib/ruby/gems/1.8/gems/rake-0.8.7/lib/rake.rb:1010:in `sh'
/opt/ruby-enterprise-1.8.7/lib/ruby/gems/1.8/gems/rake-0.8.7/lib/rake.rb:1094:in`sh'
/var/lib/jenkins/workspace/trunk_jasmine/ideeli/lib/tasks/jhw.rake:4
/opt/ruby-enterprise-1.8.7/lib/ruby/gems/1.8/gems/rake-0.8.7/lib/rake.rb:636:in `call'
/opt/ruby-enterprise-1.8.7/lib/ruby/gems/1.8/gems/rake-0.8.7/lib/rake.rb:636:in`execute'
/opt/ruby-enterprise-1.8.7/lib/ruby/gems/1.8/gems/rake-0.8.7/lib/rake.rb:631:in `each'
/opt/ruby-enterprise-1.8.7/lib/ruby/gems/1.8/gems/rake-0.8.7/lib/rake.rb:631:in`execute'
/opt/ruby-enterprise-1.8.7/lib/ruby/gems/1.8/gems/rake-0.8.7/lib/rake.rb:597:in `invoke_with_call_chain'
/opt/ruby-enterprise-1.8.7/lib/ruby/1.8/monitor.rb:242:in`synchronize'
/opt/ruby-enterprise-1.8.7/lib/ruby/gems/1.8/gems/rake-0.8.7/lib/rake.rb:590:in `invoke_with_call_chain'
/opt/ruby-enterprise-1.8.7/lib/ruby/gems/1.8/gems/rake-0.8.7/lib/rake.rb:583:in`invoke'
/opt/ruby-enterprise-1.8.7/lib/ruby/gems/1.8/gems/rake-0.8.7/lib/rake.rb:2051:in `invoke_task'
/opt/ruby-enterprise-1.8.7/lib/ruby/gems/1.8/gems/rake-0.8.7/lib/rake.rb:2029:in`top_level'
/opt/ruby-enterprise-1.8.7/lib/ruby/gems/1.8/gems/rake-0.8.7/lib/rake.rb:2029:in `each'
/opt/ruby-enterprise-1.8.7/lib/ruby/gems/1.8/gems/rake-0.8.7/lib/rake.rb:2029:in`top_level'
/opt/ruby-enterprise-1.8.7/lib/ruby/gems/1.8/gems/rake-0.8.7/lib/rake.rb:2068:in `standard_exception_handling'
/opt/ruby-enterprise-1.8.7/lib/ruby/gems/1.8/gems/rake-0.8.7/lib/rake.rb:2023:in`top_level'
/opt/ruby-enterprise-1.8.7/lib/ruby/gems/1.8/gems/rake-0.8.7/lib/rake.rb:2001:in `run'
/opt/ruby-enterprise-1.8.7/lib/ruby/gems/1.8/gems/rake-0.8.7/lib/rake.rb:2068:in`standard_exception_handling'
/opt/ruby-enterprise-1.8.7/lib/ruby/gems/1.8/gems/rake-0.8.7/lib/rake.rb:1998:in `run'
/opt/ruby-enterprise-1.8.7/lib/ruby/gems/1.8/gems/rake-0.8.7/bin/rake:31
/opt/ruby-enterprise/bin/rake:19:in`load'
/opt/ruby-enterprise/bin/rake:19
Build step 'Invoke Rake' marked build as failure
Finished: FAILURE

**Comment by johnbintz** [comment]
Are you using xvfb?

**Comment by greezeyfreezey** [comment]
I just installed xvfb because i noticed another post you were on that somebody did it but it still seems to fail.

**Comment by johnbintz** [comment]
Then I don't know what else to suggest, as I've never used xvfb. If you find out what's wrong, please post your solution somewhere so others know what to do. Gonna close this since the original problem, the missing CoffeeScript constant, is fixed.

**Comment by greezeyfreezey** [comment]
Well here is the thing.. i removed the xvfb.. and i am still getting that error for cant connect to X server.

**Comment by greezeyfreezey** [comment]
does Jasmine need X?

**Comment by johnbintz** [comment]
jasmine-headless-webkit does require an X server since it's a Qt WebKit application.

**Comment by greezeyfreezey** [comment]
so odd.. not sure whats happening then.. trying to execute directly and getting this 

./jasmine-headless-webkit -c -j /path/to/somewhere/spec/javascripts/support/jasmine.yml
'Running Jasmine specs...
jasmine-webkit-specrunner: cannot connect to X server

**Comment by johnbintz** [comment]
Unfortunately, I can't really help any more with this particular problem. I don't have any experience running truly headless apps. You'll have to find another place for help.

**Comment by greezeyfreezey** [comment]
ok thanks alot for your help.

**Comment by morganchristiansson** [comment]
greezeyfreezey: try

`xvfb-run ./jasmine-headless-webkit -c -j /path/to/somewhere/spec/javascripts/support/jasmine.yml`

**Comment by brianjolly** [comment]
xvfb-run works great. Thanks Morgan.
